cmd: shake
args:
 - install
name: shake install
targets:
  force:
    cmd: shake
    args:
      - -f
      - force
    name: force rebuild
  force-reinstall:
    cmd: shake
    args:
      - -f
      - force-reinstalls
    name: force reinstall
