notifications:
  email: false
  irc: "chat.freenode.net#Heather"

env:
 - GHCVER=8.0.1 CABALVER=1.24
 - GHCVER=head  CABALVER=1.24

matrix:
  allow_failures:
   - env: GHCVER=head  CABALVER=1.24

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 - cabal --version

install:
 - travis_retry cabal update
script:
 - cabal --version
 - cabal install --only-dependencies
 - cabal configure
 - cabal build
