install:
- cmd: 'git submodule update --init'
- ps: |
    choco install haskellplatform -version 2014.2.0.0 -y
    $env:Path += ";${env:ProgramFiles}\Haskell Platform\2014.2.0.0\bin"
    $env:Path += ";${env:ProgramFiles}\Haskell Platform\2014.2.0.0\lib\extralibs\bin"
    $env:Path += ";${env:ProgramFiles}\Haskell Platform\2014.2.0.0\mingw\bin"
    cabal update
build_script:
- ps: |
    cabal install --only-dependencies -w "C:\Program Files\Haskell Platform\2014.2.0.0\bin\ghc-7.8.3"
    cabal configure -w "C:\Program Files\Haskell Platform\2014.2.0.0\bin\ghc-7.8.3"
    cabal build
