install:
- cmd: 'git submodule update --init'
- ps: |
    choco install ghc -version 7.10.3 -y
    $env:Path += "C:\tools\ghc\ghc-7.10.3\bin"
    $env:Path += "C:\tools\ghc\ghc-7.10.3\extralibs\bin"
    $env:Path += "C:\tools\ghc\ghc-7.10.3\mingw\bin"
    cabal update
build_script:
- ps: |
    cabal install --only-dependencies -w "C:\tools\ghc\ghc-7.10.3\bin\ghc-7.10.3"
    cabal configure -w "C:\tools\ghc\ghc-7.10.3\bin\ghc-7.10.3"
    cabal build -w "C:\tools\ghc\ghc-7.10.3\bin\ghc-7.10.3"
