install:
- cmd: 'git submodule update --init'
- ps: |
    choco install ghc -version 7.10.3 -y
    $env:Path += ";${env:ProgramFiles}\ghc\7.10.3\bin"
    $env:Path += ";${env:ProgramFiles}\ghc\7.10.3\lib\extralibs\bin"
    $env:Path += ";${env:ProgramFiles}\ghc\7.10.3\mingw\bin"
    cabal update
build_script:
- ps: |
    cabal install --only-dependencies
    cabal configure
    cabal build
