flags: {}
arch: i386, x86_64
os: windows, linux
system-ghc: true
allow-newer: true
packages:
 - '.'
extra-deps:
 - base-unicode-symbols-0.2.2.4
 - utf8-string-1.0.1.1
 - despair-0.0.6
 - eternal-0.1.7
resolver: ghc-8.0.1
