flags: {}
system-ghc: true
allow-newer: true
extra-deps:
- despair-0.0.6
- eternal-0.1.4
- IfElse-0.85
- base-unicode-symbols-0.2.2.4
- conduit-1.2.6.6
- conduit-extra-1.1.13.1
- executable-path-0.0.3
- http-conduit-2.1.10.1
- http-types-0.9
- network-2.6.2.1
- optparse-applicative-0.12.1.0
- random-1.1
- resourcet-1.1.7.4
- split-0.2.3.1
- utf8-string-1.0.1.1
- vector-0.11.0.0
- yaml-0.8.17.1
- zip-archive-0.3.0.2
- aeson-0.11.2.0
- ansi-wl-pprint-0.6.7.3
- async-2.1.0
- attoparsec-0.13.0.2
- blaze-builder-0.4.0.2
- case-insensitive-1.2.0.6
- data-default-class-0.0.1
- digest-0.0.1.2
- enclosed-exceptions-1.0.1.1
- exceptions-0.8.2.1
- http-client-0.4.28
- http-client-tls-0.2.4
- lifted-base-0.2.3.6
- mmorph-1.0.6
- monad-control-1.0.1.0
- mtl-2.2.1
- old-time-1.1.0.3
- primitive-0.6.1.0
- scientific-0.3.4.6
- semigroups-0.18.1
- stm-2.4.4.1
- streaming-commons-0.1.15.4
- text-1.2.2.1
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- unordered-containers-0.2.7.0
- zlib-0.6.1.1
- ansi-terminal-0.6.2.3
- base64-bytestring-1.0.0.1
- connection-0.2.5
- cookie-0.4.2
- dlist-0.7.1.2
- fail-4.9.0.0
- hashable-1.2.4.0
- mime-types-0.1.0.7
- network-uri-2.6.1.0
- old-locale-1.0.0.7
- syb-0.6
- tagged-0.8.4
- tls-1.3.5
- asn1-encoding-0.9.3
- asn1-types-0.3.2
- byteable-0.1.1
- cereal-0.5.1.0
- cryptonite-0.15
- memory-0.12
- parsec-3.1.9
- socks-0.5.5
- x509-1.6.3
- x509-store-1.6.1
- x509-system-1.6.3
- x509-validation-1.6.3
- asn1-parse-0.9.4
- hourglass-0.2.10
- pem-0.2.2
resolver: ghc-7.10.3
